amp: true
batch_size: 256
betas: null
checkpoint_path: /content/drive/MyDrive/Mango-Mamba/results/three_phase_curriculum/phase1_combined_dataset/mango_mamba-20251209-032926/last.pth.tar
clip_grad: 1.0
crop_pct: 0.875
data_dir: combined_dataset
drop_path_rate: 0.01
early_stopping_monitor: loss
epochs: 100
eps: 1.0e-08
experiment: mango_mamba
grad_accum_steps: 16
input_size: null
log_interval: 50
lr: 0.0005
min_lr: 5.0e-06
mixer_mode: hybrid
model: mango_mamba_tiny
momentum: 0.9
num_classes: 8
opt: adamw
output: /content/drive/MyDrive/Mango-Mamba/results/three_phase_curriculum/phase1_combined_dataset
patience_epochs: 20
sched: cosine
seed: 123
smoothing: 0.01
test_split: test
train_from_checkpoint: true
train_split: train
use_eca: true
use_grn: true
use_swiglu: true
val_split: val
warmup_epochs: 5
weight_decay: 0.01
window_size:
- 7
- 7
- 7
- 7
workers: 2
